# Generated by Django 6.0.3 on 2026-06-25 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_item_rfid_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Ex: Leitor RFID COPAC Balcão', max_length=100)),
                ('token_auth', models.CharField(help_text='Token secreto que este dispositivo usa para se autenticar', max_length=64, unique=True)),
                ('is_ativo', models.BooleanField(default=True)),
                ('ultima_comunicacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_uid', models.CharField(max_length=50)),
                ('sucesso_identificacao', models.BooleanField(default=False, help_text='True se o sistema achou um Item para essa tag')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='iot.dispositivo')),
                ('item_associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
            ],
        ),
    ]
