# Generated by Django 6.0.3 on 2026-07-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(help_text='Ex: Leitor RFID COAPAC Balcão', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='token_auth',
            field=models.CharField(blank=True, help_text='Token secreto que este dispositivo usa para se autenticar', max_length=64, unique=True),
        ),
    ]
