# Generated by Django 6.0.3 on 2026-06-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_acaolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rfid_uid',
            field=models.CharField(blank=True, db_index=True, help_text='UID da etiqueta RFID associada ao item', max_length=50, null=True),
        ),
    ]
