# Generated by Django 6.0.3 on 2026-06-25 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_latitude_item_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, help_text='URL para onde a notificação deve redirecionar', max_length=255, null=True)),
                ('icone', models.CharField(default='bi-bell-fill', help_text='Classe de ícone do Bootstrap Icons', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'find_notificacao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
